spring.application.name=zongz

## - h2 database connection
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
# - spring.datasource.url=jdbc:h2:file:/data/demo    <-- file based storage

## - jpa / hibernate properties
spring.h2.console.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

## - h2 console
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.path=/h2-console

## – upload directory
audio.store.upload-dir=uploads/audio

## – upload specs
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

## postresql / pgvector database connection
# spring.datasource.url=jdbc:postgresql://localhost:5432/audiodb
# spring.datasource.driverClassName=org.postgresql.Driver
# spring.datasource.username=your_postgres_user
# spring.datasource.password=your_postgres_password
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.hibernate.ddl-auto=update
